apiVersion: v1
kind: Service
metadata:
  namespace: pinglog-namespace
  name: pingpong-service
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 3033
      protocol: TCP
      targetPort: 3033