apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pinglog-namespace
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
