apiVersion: batch/v1
kind: CronJob
metadata:
  namespace:  backup
  name: backup-db
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-cronjob
            image: google/cloud-sdk:slim
            command: ["/script/backup-script.sh"]
            volumeMounts:
              - name: script
                mountPath: "/script"
              - name: temp
                mountPath: "/etc/temp"
            env:
              - name: SERVICE_ACCOUNT_KEY
                valueFrom:
                  secretKeyRef:
                    name: gc-secret
                    key: SERVICE_ACCOUNT_KEY
              - name: DB_URL
                valueFrom:
                  secretKeyRef:
                    name: todo-secret
                    key: DB_URL
          volumes:
            - name: script
              configMap:
                name: backup-configmap
                defaultMode: 0777
            - name: temp
              emptyDir: {}
          restartPolicy: Never