apiVersion: v1
kind: Service
metadata:
  namespace: pinglog-namespace
  name: log-reader-service
spec:
  type: ClusterIP
  selector:
    app: log-reader
  ports:
    - port: 3021
      protocol: TCP
      targetPort: 3022