apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: log-output
spec:
  template:
    spec:
      containers:
      - image: viksil/log_output:5.07
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "30m"
            memory: "130Mi"
        env:
          - name: LOG_PORT
            value: "8080"
        ports:
        - containerPort: 8080

