apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-cfgmap
  namespace: pinglog-namespace
data:
  message: "hello world"
  information.txt: |
    file.content=this text is from file
  backend-host: "localhost"
   