apiVersion: v1
kind: Service
metadata:
  namespace: pinglog-namespace
  name: log-output-service
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 3010
      protocol: TCP
      targetPort: 3011