apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/IMAGE_BACKEND
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-cfgmap
                  key: port
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: DB_URL  