apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pinglog-namespace
  name: pingpong-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: viksil/pingpong:4.01
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "30m"
              memory: "130Mi"
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: pingpong-secret
                  key: DB_URL
          readinessProbe:
            initialDelaySeconds: 180 
            periodSeconds: 10
            httpGet:
               path: /healthz
               port: 3033