apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: todo-namespace
  name: todo-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/todo"