apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo-namespace
  name: todo-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi