apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"generation":1,"name":"todo-backend-depl","namespace":"todo-namespace","resourceVersion":"11735","uid":"2372cb91-0fc4-46c8-9005-3d1f6f93c63c"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"todo-backend"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"config.linkerd.io/enable-external-profiles":"true","linkerd.io/inject":"enabled"},"labels":{"app":"todo-backend"}},"spec":{"containers":[{"env":[{"name":"PORT","valueFrom":{"configMapKeyRef":{"key":"port","name":"todo-cfgmap"}}},{"name":"DB_URL","valueFrom":{"secretKeyRef":{"key":"DB_URL","name":"todo-secret"}}}],"image":"viksil/todo_backend:4.05","imagePullPolicy":"Always","livenessProbe":{"exec":{"command":["sh","-c","wget --spider -S \"http://0.0.0.0:$PORT/healthz\" 2\u003e\u00261 | grep \"HTTP/\" | awk '{print $2}'"]},"failureThreshold":3,"initialDelaySeconds":300,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"todo-backend","readinessProbe":{"exec":{"command":["sh","-c","wget --spider -S \"http://0.0.0.0:$PORT/healthz\" 2\u003e\u00261 | grep \"HTTP/\" | awk '{print $2}'"]},"failureThreshold":3,"initialDelaySeconds":180,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"todo-backend-depl-6c49c7d5\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-01-17T19:39:35Z"
  generation: 2
  name: todo-backend-depl
  namespace: todo-namespace
  resourceVersion: "18103"
  uid: 2372cb91-0fc4-46c8-9005-3d1f6f93c63c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        config.linkerd.io/enable-external-profiles: "true"
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: todo-backend
    spec:
      containers:
      - env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: port
              name: todo-cfgmap
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: DB_URL
              name: todo-secret
        image: viksil/todo_backend:4.05
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - wget --spider -S "http://0.0.0.0:$PORT/healthz" 2>&1 | grep "HTTP/"
              | awk '{print $2}'
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: todo-backend
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - wget --spider -S "http://0.0.0.0:$PORT/healthz" 2>&1 | grep "HTTP/"
              | awk '{print $2}'
          failureThreshold: 3
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-17T19:42:46Z"
    lastUpdateTime: "2025-01-17T19:42:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-17T19:39:35Z"
    lastUpdateTime: "2025-01-17T21:18:52Z"
    message: ReplicaSet "todo-backend-depl-7c5ffd6c7c" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1