apiVersion: v1
kind: Service
metadata:
  namespace: pinglog-namespace
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres-port
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres
