apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pinglog-namespace
  name: pingpong-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi