apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume-claim
spec:
  storageClassName: shared-volume-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi